# Basic Information 
title: Xiaoyu Chu
position: Ph.D. Student
affiliation: Vrije University Amsterdam
affiliation_link: https://www.vu.nl/en/
# affiliation_logo: ./assets/img/vu-circle.png
email: chuxiaoyu123 (at) gmail.com

# Search Engine Optimization (SEO)
keywords: Xiaoyu Chu, xiaoyu chu, chu xiaoyu, chuxiaoyu
canonical: https://chuxiaoyu.github.io
description: https://chuxiaoyu.github.io

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=eIKz6sMAAAAJ&hl=en
github_link: https://github.com/chuxiaoyu
linkedin: https://www.linkedin.com/in/chuxiaoyu/
cv_link: https://chuxiaoyu.github.io/assets/pdf/CV_DS_XiaoyuChu.pdf

# Images 
avatar: ./assets/img/xchu.png
favicon: ./assets/img/pikachu.png
favicon_dark: ./assets/img/pikachu.png

# Footnotes
enable_footnote: true
footnote: "This website is built based on the <a href='https://github.com/yaoyao-liu/minimal-light'>Minimal Light</a>."
footnote_link: https://github.com/yaoyao-liu/minimal-light

auto_dark_mode: true

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: VdKD5xBKdzCyh4frXOxQKpE5rFZXuZ9Kot9yZaYenAc

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME

markdown: kramdown
kramdown:
  input: GFM

# Use short blog URLs like /blogs/my-post
permalink: /blogs/:slug
